# Generated by Django 4.2.6 on 2023-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("pin", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PK-JK", "Azad Jammu & Kashmir"),
                            ("PK-BA", "Balochistan"),
                            ("PK-TA", "Federally Administered Tribal Areas"),
                            ("PK-GB", "Gilgit-Baltistan"),
                            ("PK-IS", "Islamabad"),
                            ("PK-KP", "Khyber Pakhtunkhwa"),
                            ("PK-PB", "Punjab"),
                            ("PK-SD", "Sindh"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mobile", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("job_city", models.CharField(max_length=50)),
                ("profile_img", models.ImageField(blank=True, upload_to="profile_img")),
            ],
        ),
    ]
