# Generated by Django 4.2.6 on 2023-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="resume_file",
            field=models.FileField(blank=True, upload_to="doc,"),
        ),
    ]
