# Generated by Django 4.2.6 on 2023-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_resume", "0002_resume_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="resume_file",
            field=models.FileField(blank=True, upload_to="doc"),
        ),
    ]
