# Generated by Django 4.2.6 on 2023-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_resume", "0003_alter_resume_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="job_city",
            field=models.CharField(
                choices=[
                    ("Lahore", "Lahore"),
                    ("Islamabad", "Islamabad"),
                    ("Multan", "Multan"),
                    ("Karachi", "Karachi"),
                    ("Rawalpindi", "Rawalpindi"),
                ],
                max_length=50,
            ),
        ),
    ]
