# Generated by Django 4.2.6 on 2023-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_resume", "0004_alter_resume_job_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="job_city",
            field=models.CharField(max_length=50),
        ),
    ]
